import java.awt.EventQueue;
import java.awt.SystemColor;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ContainerAdapter;
import java.awt.event.ContainerEvent;

import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import javax.swing.JTree;
import javax.swing.border.EmptyBorder;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.TreePath;
import javax.swing.tree.TreeSelectionModel;

//Much of this class was auto-generated by eclipse's window-maker
public class Admin extends JFrame 
{
	private JPanel contentPane;
	private User user;
	private DefaultMutableTreeNode node;
	//Tree is public so others can access
	public JTree tree = new JTree();
		
	public void run()
	{
		EventQueue.invokeLater(new Runnable() 
		{
			public void run() 
			{
				try
				{
					Admin frame = new Admin();
					frame.setVisible(true);
				} 
				catch (Exception e)
				{
					e.printStackTrace();
				}
			}
		});
	}

	public Admin(User user, DefaultMutableTreeNode node) 
	{
		this.user = user;
		this.node = node;
	}
	
	public Admin()
	{
		//Create window
		setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		setBounds(200, 200, 600, 400);
		contentPane = new JPanel();
		contentPane.setBackground(SystemColor.activeCaption);
		contentPane.setBorder(new EmptyBorder(5, 5, 5, 5));
		setContentPane(contentPane);
		contentPane.setLayout(null);
		
		//Create tree
		tree.setEditable(true);
		tree.getSelectionModel().setSelectionMode(TreeSelectionModel.SINGLE_TREE_SELECTION);
		tree.setShowsRootHandles(true);
		tree.setBounds(0, 0, 188, 362);
		contentPane.add(tree);
		
		//Create objects
		JTextArea userNameInputArea = new JTextArea();
		final JLabel addUserLabel = new JLabel();
		JTextArea userGroupInputArea = new JTextArea();
		final JLabel addUserGroupLabel = new JLabel();
		DefaultListModel<String> model = new DefaultListModel<String>();
		
		//Add user button
		JButton addUserButt = new JButton("Add User");
		addUserButt.addActionListener(new ActionListener()
		{
			public void actionPerformed(ActionEvent arg0)
			{
				String userNameInput = addUserLabel.getText();
				if()
			}
		});
		addUserButt.setBounds(386, 6, 188, 50);
		contentPane.add(addUserButt);
		
		//Adds User Group button
		JButton addUserGrpButt = new JButton("Add Group");
		addUserGrpButt.addActionListener(new ActionListener()
		{
			public void actionPerformed(ActionEvent arg0)
			{
				userGroupInputArea.setText(addUserGroupLabel.getText());
				System.out.println("Group added! Woohoo!");
			}
		});
		addUserGrpButt.setBounds(386, 67, 188, 50);
		contentPane.add(addUserGrpButt);
		
		//Opens the UserUI
		JButton opnUsrView = new JButton("Open User View");
		opnUsrView.addActionListener(new ActionListener()
		{
			public void actionPerformed(ActionEvent arg0)
			{
				UserUI userCP = new UserUI();
				userCP.run();
				dispose();
				contentPane.setVisible(true);
			}
		});
		opnUsrView.setBounds(198, 141, 376, 50);
		contentPane.add(opnUsrView);
		
		//Show total users button
		JButton showUserTtlButt = new JButton("Show User Total");
		showUserTtlButt.addActionListener(new ActionListener()
		{
			public void actionPerformed(ActionEvent arg0)
			{
				
			}
		});
		showUserTtlButt.setBounds(198, 220, 176, 50);
		contentPane.add(showUserTtlButt);
		
		//Show Group Total Button
		JButton showTtlGrpsButt = new JButton("Show Group Total");
		showTtlGrpsButt.addActionListener(new ActionListener()
		{
			public void actionPerformed(ActionEvent arg0)
			{
				
			}
		});
		showTtlGrpsButt.setBounds(386, 220, 188, 50);
		contentPane.add(showTtlGrpsButt);
		
		//Show total # of messages button
		JButton showTtlMsgButt = new JButton("Show Messages Total");
		showTtlMsgButt.addActionListener(new ActionListener()
		{
			public void actionPerformed(ActionEvent arg0) 
			{
				
			}
		});
		showTtlMsgButt.setBounds(198, 281, 176, 50);
		contentPane.add(showTtlMsgButt);
		
		//Show Positive Percentage button
		JButton showPosPercButt = new JButton("Show Positive Percentage");
		showPosPercButt.addActionListener(new ActionListener() 
		{
			public void actionPerformed(ActionEvent arg0)
			{
				
			}
		});
		showPosPercButt.setBounds(386, 281, 188, 50);
		contentPane.add(showPosPercButt);
		
		/*textArea.addContainerListener(new ContainerAdapter()
		{
			public void componentAdded(ContainerEvent arg0)
			{
				
			}
		});*/
		userNameInputArea.setBounds(198, 21, 162, 35);
		contentPane.add(userNameInputArea);
		
		userGroupInputArea.setBounds(198, 82, 162, 35);
		contentPane.add(userGroupInputArea);
		
		JLabel lblEnterUserId = new JLabel("Enter User ID:");
		lblEnterUserId.setBounds(199, 1, 103, 22);
		contentPane.add(lblEnterUserId);
		
		JLabel lblEnterGroupId = new JLabel("Enter Group ID:");
		lblEnterGroupId.setBounds(198, 67, 76, 14);
		contentPane.add(lblEnterGroupId);
	}
}
