
import java.awt.BorderLayout;
import java.awt.EventQueue;

import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;
import javax.swing.DefaultListModel;
import javax.swing.JLabel;
import javax.swing.JTextArea;
import javax.swing.JButton;
import javax.swing.JList;

import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.awt.event.ContainerAdapter;
import java.awt.event.ContainerEvent;
import java.awt.Color;
import java.awt.SystemColor;

//Much of this class was auto-generated by eclipse's window-maker
public class UserUI extends JFrame
{

	private JPanel contentPane;
	private UserUI ui;
	private User user;
		
	public void run()
	{
		EventQueue.invokeLater(new Runnable()
		{
			public void run() 
			{
				try 
				{
					UserUI frame = new UserUI();
					frame.setVisible(true);
				} 
				catch (Exception e) 
				{
					e.printStackTrace();
				}
			}
		});
	}
	//Copy a pre-existing ui
	public UserUI(UserUI ui, User user) 
	{
		this.ui = ui;
		this.user = user;
	}
	
	public UserUI() 
	{
		//Initialize the window
		setBackground(Color.WHITE);
		setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		setBounds(100, 100, 450, 400);
		contentPane = new JPanel();
		contentPane.setBackground(SystemColor.activeCaption);
		contentPane.setBorder(new EmptyBorder(5, 5, 5, 5));
		setContentPane(contentPane);
		contentPane.setLayout(null);
		
		
		JTextArea followArea = new JTextArea();
		final JLabel followLabel = new JLabel();
		JTextArea tweetArea = new JTextArea();
		final JLabel tweetLabel = new JLabel();
		
		//Follow Button
		JButton btnFollowUser = new JButton("Follow User");
		btnFollowUser.addActionListener(new ActionListener() 
		{
			public void actionPerformed(ActionEvent arg0) 
			{
				followArea.setText(followLabel.getText());
				System.out.println("Stalking User!");
			}
		});
		btnFollowUser.setBounds(233, 10, 204, 36);
		contentPane.add(btnFollowUser);
		
		followArea.addContainerListener(new ContainerAdapter() 
		{
			public void componentAdded(ContainerEvent arg0) 
			{
				
			}
		});
		followArea.setBounds(10, 12, 194, 34);
		contentPane.add(followArea);
		
		DefaultListModel<String> model = new DefaultListModel<String>();
		JList list = new JList();
		list.setBounds(10, 68, 427, 91);
		contentPane.add(list);
		
		tweetArea.setBounds(10, 170, 235, 52);
		contentPane.add(tweetArea);
		
		JList<String> tweets = new JList<String>();
		
		JButton btnTweet = new JButton("Post Tweet");
		btnTweet.addActionListener( new ActionListener() 
		{
			public void actionPerformed(ActionEvent arg0)
			{
				tweetArea.setText(tweetLabel.getText());
				System.out.println("Posted Tweet!");
				//tweets.add(textArea_1.getText());
			}
		});
		btnTweet.setBounds(274, 170, 163, 45);
		contentPane.add(btnTweet);
		
		DefaultListModel<String> model2 = new DefaultListModel<String>();
		JList list_1 = new JList();
		list_1.setBounds(10, 233, 427, 136);
		contentPane.add(list_1);
	}
}
