
import java.awt.BorderLayout;
import java.awt.EventQueue;

import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;
import javax.swing.DefaultListModel;
import javax.swing.JLabel;
import javax.swing.JTextArea;
import javax.swing.JButton;
import javax.swing.JList;

import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.awt.event.ContainerAdapter;
import java.awt.event.ContainerEvent;
import java.awt.Color;
import java.awt.SystemColor;

//Much of this class was auto-generated by eclipse's window-maker
public class UserUI extends JFrame
{

	private JPanel contentPane;
	private User user;
	
	public UserUI(User selectedUser) 
	{
		user = selectedUser;
		
		//Initialize the window
		setBackground(Color.WHITE);
		setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		setBounds(100, 100, 450, 400);
		contentPane = new JPanel();
		contentPane.setBackground(SystemColor.activeCaption);
		contentPane.setBorder(new EmptyBorder(5, 5, 5, 5));
		setContentPane(contentPane);
		contentPane.setLayout(null);
		
		//Init ui components
		final JTextArea followArea = new JTextArea();
		followArea.setEditable(true);
		final JLabel followLabel = new JLabel();
		final JTextArea tweetArea = new JTextArea();
		final JLabel tweetLabel = new JLabel();
		
		//Follow Button
		JButton btnFollowUser = new JButton("Follow User");
		btnFollowUser.addActionListener(new ActionListener() 
		{
			public void actionPerformed(ActionEvent arg0) 
			{
				
			}
		});
		btnFollowUser.setBounds(200, 10, 200, 30);
		contentPane.add(btnFollowUser);
		
		followArea.setBounds(10, 10, 190, 30);
		contentPane.add(followArea);
				
		tweetArea.setBounds(10, 170, 230, 50);
		contentPane.add(tweetArea);
		
		JList<String> tweets = new JList<String>();
		
		JButton btnTweet = new JButton("Post Tweet");
		btnTweet.addActionListener( new ActionListener() 
		{
			public void actionPerformed(ActionEvent arg0)
			{
				
			}
		});
		btnTweet.setBounds(270, 170, 160, 40);
		contentPane.add(btnTweet);
		
		DefaultListModel<String> model2 = new DefaultListModel<String>();
		JList list_1 = new JList();
		list_1.setBounds(10, 233, 427, 136);
		contentPane.add(list_1);
	}
	
	public void run()
	{
		EventQueue.invokeLater(new Runnable()
		{
			public void run() 
			{
				try 
				{
					UserUI frame = new UserUI(user);
					frame.setVisible(true);
				} 
				catch (Exception e) 
				{
					e.printStackTrace();
				}
			}
		});
	}
}
