
import java.awt.BorderLayout;
import java.awt.EventQueue;

import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;
import javax.swing.DefaultListModel;
import javax.swing.JLabel;
import javax.swing.JTextArea;
import javax.swing.JButton;
import javax.swing.JList;

import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.awt.event.ContainerAdapter;
import java.awt.event.ContainerEvent;
import java.awt.Color;
import java.awt.SystemColor;

//Much of this class was auto-generated by eclipse's window-maker
public class UserUI extends JFrame
{

	private JPanel contentPane;
	private User user;
	
	public UserUI(User selectedUser) 
	{
		user = selectedUser;
		
		//Initialize the window
		setBackground(Color.WHITE);
		setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		setBounds(100, 100, 450, 400);
		contentPane = new JPanel();
		contentPane.setBackground(SystemColor.activeCaption);
		contentPane.setBorder(new EmptyBorder(5, 5, 5, 5));
		setContentPane(contentPane);
		contentPane.setLayout(null);
		
		//Init ui components
		final JTextArea followArea = new JTextArea();
		followArea.setEditable(true);
		final JLabel followLabel = new JLabel();
		final JTextArea followingArea = new JTextArea();
		followingArea.setText(user.followingList());
		followingArea.setEditable(false);
		final JTextArea tweetArea = new JTextArea();
		final JLabel tweetLabel = new JLabel();
		final JTextArea newsFeedArea = new JTextArea();
		
		//Follow Button Follow User Button
		JButton btnFollowUser = new JButton("Follow User");
		btnFollowUser.addActionListener(new ActionListener() 
		{
			public void actionPerformed(ActionEvent arg0) 
			{
				User newFollow = Admin.instance.rootGroup.findUser(followArea.getText(), Admin.instance.rootGroup);
				user.followUser(newFollow);
				newFollow.followed(user);
				followingArea.setText(user.followingList());
			}
		});
		btnFollowUser.setBounds(200, 10, 200, 30);
		contentPane.add(btnFollowUser);
		
		//Creat text areas
		followArea.setBounds(10, 10, 190, 30);
		contentPane.add(followArea);
		
		followingArea.setBounds(10, 45, 300, 100);
		followingArea.setEditable(false);
		contentPane.add(followingArea);
		
		tweetArea.setBounds(10, 170, 230, 50);
		contentPane.add(tweetArea);
		
		newsFeedArea.setBounds(10, 230, 300, 100);
		newsFeedArea.setEditable(false);
		newsFeedArea.setText(user.newsFeedString());
		contentPane.add(newsFeedArea);
		
		//Post tweet button
		JButton btnTweet = new JButton("Post Tweet");
		btnTweet.addActionListener( new ActionListener() 
		{
			public void actionPerformed(ActionEvent arg0)
			{
				user.writeTweet(tweetArea.getText());
				newsFeedArea.setText(user.newsFeedString());
			}
		});
		btnTweet.setBounds(270, 170, 160, 40);
		contentPane.add(btnTweet);
	}
	
	//open the userUI
	public void run()
	{
		EventQueue.invokeLater(new Runnable()
		{
			public void run() 
			{
				try 
				{
					UserUI frame = new UserUI(user);
					frame.setVisible(true);
				} 
				catch (Exception e) 
				{
					e.printStackTrace();
				}
			}
		});
	}
}
